<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function countComment() {
        $query = $this->createQueryBuilder('comment')->select('COUNT(comment)')->getQuery();
        return $query->getSingleScalarResult();
    }
}
